version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: Hostname
        container_name: Kopia
        restart: unless-stopped
        ports:
            - 7001:7001
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:7001
            - --server-username=admin
            - --server-password=15717253197
        environment:
            # Set repository password
            KOPIA_PASSWORD: "SECRET"
            USER: "User"
        volumes:
            # Mount local folders needed by kopia
            - /opt/backup/kopia/config:/app/config
            - /opt/backup/kopia/cache:/app/cache
            - /opt/backup/kopia/logs:/app/logs
            # Mount local folders to snapshot
            - /opt/backup/kopia/data:/data:ro
            # Mount repository location
            - /opt/backup/kopia/repository:/repository
            - /var/lib/lxd/backups:/lxdbak
            # Mount path for browsing mounted snapshots
            - /opt/backup/kopia/tmp:/tmp:shared
